export default {
"20MICRONS.BSE":	"20 Microns Limited",
"21STCENMGM.BSE":"Twentyfirst Century Management Services Limited",
"3IINFOTECH.BSE":"3i Infotech Limited",
"3MINDIA.BSE":"3M India Limited",
"5PAISA.BSE":"5paisa Capital Limited",
"63MOONS.BSE":"63 moons technologies limited",
"8KMILES.BSE":"8K Miles Software Services Limited",
"A2ZINFRA.BSE":"A2Z Infra Engineering Limited",
"AARTIDRUGS.BSE":"Aarti Drugs Limited",
"AARTIIND.BSE":"Aarti Industries Limited",
"AARVEEDEN.BSE":"Aarvee Denims and Exports Limited",
"ABAN.BSE":"Aban Offshore Limited",
"ABB.BSE":"ABB India Limited",
"ABBOTINDIA.BSE":"Abbott India Limited",
"ABCAPITAL.BSE":"Aditya Birla Capital Limited",
"ABFRL.BSE":"Aditya Birla Fashion and Retail Limited",
"ACE.BSE":"Action Construction Equipment Limited",
}